/* eslint-disable react/display-name */
"use client";

import React, { useEffect, useCallback } from "react";
import {
  DailyAudioTrack,
  DailyVideo,
  useDevices,
  useLocalSessionId,
  useMeetingState,
  useScreenVideoTrack,
  useVideoTrack
} from "@daily-co/daily-react";

import { MicSelectBtn, CameraSelectBtn, ScreenShareButton } from "../device-select";
import { useLocalScreenshare } from "../../hooks/use-local-screenshare";
import { useReplicaIDs } from "../../hooks/use-replica-ids";
import { useCVICall } from "../../hooks/use-cvi-call";
import { AudioWave } from "../audio-wave";
import styles from "./conversation.module.css";

// ✅ Tool implementations
import { getAccountProfile, forecastRenewal, generateStrategy } from "../../../../../lib/tools";

// ✅ Event hooks (generated by: npx @tavus/cvi-ui@latest add cvi-events-hooks)
// If this import fails, search your repo for "useObservableEvent" and update the path.
import { useObservableEvent, useSendAppMessage } from "../../hooks/cvi-events-hooks";

interface ConversationProps {
  onLeave: () => void;
  conversationUrl: string;
}

const VideoPreview = React.memo(({ id }: { id: string }) => {
  const videoState = useVideoTrack(id);
  const widthVideo = videoState.track?.getSettings()?.width;
  const heightVideo = videoState.track?.getSettings()?.height;
  const isVertical = widthVideo && heightVideo ? widthVideo < heightVideo : false;

  return (
    <div
      className={`${styles.previewVideoContainer} ${
        isVertical ? styles.previewVideoContainerVertical : ""
      } ${videoState.isOff ? styles.previewVideoContainerHidden : ""}`}
    >
      <DailyVideo
        automirror
        sessionId={id}
        type="video"
        className={`${styles.previewVideo} ${
          isVertical ? styles.previewVideoVertical : ""
        } ${videoState.isOff ? styles.previewVideoHidden : ""}`}
      />
      <div className={styles.audioWaveContainer}>
        <AudioWave id={id} />
      </div>
    </div>
  );
});

const PreviewVideos = React.memo(() => {
  const localId = useLocalSessionId();
  const { isScreenSharing } = useLocalScreenshare();
  const replicaIds = useReplicaIDs();
  const replicaId = replicaIds[0];

  return (
    <>
      {isScreenSharing && <VideoPreview id={replicaId} />}
      <VideoPreview id={localId} />
    </>
  );
});

const MainVideo = React.memo(() => {
  const replicaIds = useReplicaIDs();
  const localId = useLocalSessionId();
  const videoState = useVideoTrack(replicaIds[0]);
  const screenVideoState = useScreenVideoTrack(localId);
  const isScreenSharing = !screenVideoState.isOff;
  const replicaId = replicaIds[0];

  if (!replicaId) {
    return (
      <div className={styles.waitingContainer}>
        <p>Connecting...</p>
      </div>
    );
  }

  return (
    <div
      className={`${styles.mainVideoContainer} ${
        isScreenSharing ? styles.mainVideoContainerScreenSharing : ""
      }`}
    >
      <DailyVideo
        automirror
        sessionId={isScreenSharing ? localId : replicaId}
        type={isScreenSharing ? "screenVideo" : "video"}
        className={`${styles.mainVideo}
          ${isScreenSharing ? styles.mainVideoScreenSharing : ""}
          ${videoState.isOff ? styles.mainVideoHidden : ""}`}
      />
      <DailyAudioTrack sessionId={replicaId} />
    </div>
  );
});

export const Conversation = React.memo(({ onLeave, conversationUrl }: ConversationProps) => {
  const { joinCall, leaveCall } = useCVICall();
  const meetingState = useMeetingState();
  const { hasMicError } = useDevices();

  // ✅ Send messages/events back to Tavus
  const sendAppMessage = useSendAppMessage();

  // Leave on call error
  useEffect(() => {
    if (meetingState === "error") onLeave();
  }, [meetingState, onLeave]);

  // ✅ Join when URL is available
  useEffect(() => {
    if (!conversationUrl) return;
    joinCall({ url: conversationUrl });
  }, [conversationUrl, joinCall]);

  const handleLeave = useCallback(() => {
    leaveCall();
    onLeave();
  }, [leaveCall, onLeave]);

  // ✅ Handle Tavus tool calls: conversation.tool_call -> run local function -> conversation.respond
  useObservableEvent(async (event: any) => {
    if (!event || event.message_type !== "conversation") return;
    if (event.event_type !== "conversation.tool_call") return;

    const conversation_id = event.conversation_id;
    const toolName = event?.properties?.name;
    const argsRaw = event?.properties?.arguments;

    let args: any = {};
    try {
      args = typeof argsRaw === "string" ? JSON.parse(argsRaw) : (argsRaw ?? {});
    } catch {
      args = {};
    }

    let result: any = null;

    try {
      switch (toolName) {
        case "get_account_profile": {
          const q = args?.query ?? args?.name ?? args?.domain ?? "";
          const profile = getAccountProfile(String(q));
          result = profile ?? { error: `No account found for '${q}'` };
          break;
        }

        case "forecast_renewal": {
          // The model might pass:
          // - the metrics directly, OR
          // - { metrics: {...} }, OR
          // - a full profile object
          const payload = args?.metrics ?? args?.profile ?? args ?? {};
          result = forecastRenewal(payload);
          break;
        }

        case "generate_strategy": {
          const payload = args?.forecast ?? args ?? {};
          result = generateStrategy(payload);
          break;
        }

        default:
          result = { error: `Unknown tool: ${toolName}` };
      }
    } catch (err: any) {
      result = { error: err?.message ?? "Tool execution failed" };
    }

    // Send tool result back so the persona can continue.
    sendAppMessage({
      message_type: "conversation",
      event_type: "conversation.respond",
      conversation_id,
      properties: {
        text: `TOOL_RESULT ${toolName}: ${JSON.stringify(result)}`
      }
    });
  });

  return (
    <div className={styles.container}>
      <div className={styles.videoContainer}>
        {hasMicError && (
          <div className={styles.errorContainer}>
            <p>Camera or microphone access denied. Please check your settings and try again.</p>
          </div>
        )}

        <div className={styles.mainVideoContainer}>
          <MainVideo />
        </div>

        <div className={styles.selfViewContainer}>
          <PreviewVideos />
        </div>
      </div>

      <div className={styles.footer}>
        <div className={styles.footerControls}>
          <MicSelectBtn />
          <CameraSelectBtn />
          <ScreenShareButton />
          <button type="button" className={styles.leaveButton} onClick={handleLeave}>
            <span className={styles.leaveButtonIcon}>
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                role="img"
                aria-label="Leave Call"
              >
                <path
                  d="M18 6L6 18M6 6L18 18"
                  stroke="currentColor"
                  strokeWidth="2"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                />
              </svg>
            </span>
          </button>
        </div>
      </div>
    </div>
  );
});